name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Spring Boot Backend
      run: |
        cd backend
        mvn clean package -DskipTests

    - name: Build Angular Frontend
      run: |
        cd frontend
        npm install -g @angular/cli
        npm install
        ng build --prod

    - name: Deploy Backend to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-backend-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: backend/target/*.jar

    - name: Deploy Frontend to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-frontend-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: frontend/dist
